# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 10:41
from __future__ import unicode_literals

from django.db import migrations, models

def create_data(apps, schemae_edtior):
    User = apps.get_model(settings.Member)
    user = User(id = 1, username="dylansyj@gmail.com", password="Cookies1")
    user.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(create_data),
    ]
